// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarkov.API.Database;

#nullable disable

namespace Tarkov.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250214222152_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tarkov.API.Database.Entities.AchievementEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<float>("AdjustedPlayersCompletedPercentage")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionTranslationKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("PlayersCompletedPercentage")
                        .HasColumnType("real");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionTranslationKey")
                        .IsUnique();

                    b.HasIndex("NameTranslationKey")
                        .IsUnique();

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Tarkov.API.Database.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("LastRun")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LastRunSuccessful")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NextScheduledRun")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Tarkov.API.Database.Entities.TaskExecutionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntitiesCreated")
                        .HasColumnType("int");

                    b.Property<int>("EntitiesDeleted")
                        .HasColumnType("int");

                    b.Property<int>("EntitiesUpdated")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskExecutions");
                });

            modelBuilder.Entity("Tarkov.API.Database.Entities.TranslationEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Language")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Key", "Language");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("Tarkov.API.Database.Entities.TranslationKeyEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Key");

                    b.ToTable("TranslationKeys");
                });

            modelBuilder.Entity("Tarkov.API.Database.Entities.AchievementEntity", b =>
                {
                    b.HasOne("Tarkov.API.Database.Entities.TranslationKeyEntity", "DescriptionTranslationKeyEntity")
                        .WithOne("AchievementDescription")
                        .HasForeignKey("Tarkov.API.Database.Entities.AchievementEntity", "DescriptionTranslationKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tarkov.API.Database.Entities.TranslationKeyEntity", "NameTranslationKeyEntity")
                        .WithOne("AchievementName")
                        .HasForeignKey("Tarkov.API.Database.Entities.AchievementEntity", "NameTranslationKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DescriptionTranslationKeyEntity");

                    b.Navigation("NameTranslationKeyEntity");
                });

            modelBuilder.Entity("Tarkov.API.Database.Entities.TaskExecutionEntity", b =>
                {
                    b.HasOne("Tarkov.API.Database.Entities.TaskEntity", "Task")
                        .WithMany("Executions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Tarkov.API.Database.Entities.TranslationEntity", b =>
                {
                    b.HasOne("Tarkov.API.Database.Entities.TranslationKeyEntity", "KeyEntity")
                        .WithMany("Translations")
                        .HasForeignKey("Key")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KeyEntity");
                });

            modelBuilder.Entity("Tarkov.API.Database.Entities.TaskEntity", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("Tarkov.API.Database.Entities.TranslationKeyEntity", b =>
                {
                    b.Navigation("AchievementDescription");

                    b.Navigation("AchievementName");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
